export const ProjectsListData = [
  {
    id: "01",
    key: 1,
    name: "avicta co",
    detail: "digital agency website",
    imgurl: "/images/Avicta.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "02",
    key: 2,
    name: "zartaj",
    detail: "landing page for UAE comapny",
    imgurl: "/images/Avicta.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "03",
    key: 3,
    name: "noor ul huda",
    detail: "abc",
    imgurl: "/images/Avicta.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "04",
    key: 4,
    name: "avicta co",
    detail: "abc",
    imgurl: "/images/Avicta.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "05",
    key: 5,
    name: "color pal",
    detail: "abc",
    imgurl: "/images/Avicta.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "06",
    key: 6,
    name: "avicta co",
    detail: "abc",
    imgurl: "/images/Avicta.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
];

// import { AiFillGithub, AiFillFire } from "react-icons/ai";
// import { FaNodeJs, FaReact, FaPython } from "react-icons/fa";
// import { FaMobileAlt } from "react-icons/fa";
// import { FaSass } from "react-icons/fa";
// import {
//   SiJavascript,
//   SiTypescript,
//   SiDjango,
//   SiPython,
//   SiWebpack,
//   SiStyledComponents,
//   SiFramer,
//   SiHtml5,
//   SiNextDotJs,
// } from "react-icons/si";
// import { DiDjango } from "react-icons/di";

// const ProjectsListData = [
//   {
//     id: "01",
//     key: 1,
//     name: "avicta co",
//     detail: "digital agency website",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "02",
//     key: 2,
//     name: "zartaj",
//     detail: "landing page for UAE comapny",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "03",
//     key: 3,
//     name: "noor ul huda",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "04",
//     key: 4,
//     name: "avicta co",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "05",
//     key: 5,
//     name: "color pal",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "06",
//     key: 6,
//     name: "avicta co",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
// ];

// export default ProjectsListData;

// export const Products = {
//   product1: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product2: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product3: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product4: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product5: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product6: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product7: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product8: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product9: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
//   product10: {
//     name: "abc",
//     price: 12,
//     available: true,
//     stock: 10,
//     description: "asdasaaadsjadjjajdkjkjdkjdsakjskjskjsdakjsdjksd",
//     color: [],
//     imageurl: "",
//   },
// };
