export const ProjectsListData = [
  {
    id: "01",
    key: 1,
    name: "ColorPal",
    detail: "color library website",
    imgurl: "/logo/colorpallogo.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "02",
    key: 2,
    name: "Zartaj Traders",
    detail: "landing page for UAE comapny",
    imgurl: "/logo/zartaj.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "03",
    key: 3,
    name: "Noor Al Huda",
    detail: "UAE brand Website",
    imgurl: "/logo/nahlogo.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "04",
    key: 4,
    name: "Zartaj Collections",
    detail: "designer clothes website",
    imgurl: "/logo/collections.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "05",
    key: 5,
    name: "Earbudsz",
    detail: "earphone blog web",
    imgurl: "/logo/earbudsz.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  {
    id: "06",
    key: 6,
    name: "Al qamesh",
    detail: "E-commerce website",
    imgurl: "/logo/alqamesh.png",
    url: "#",
    githuburl: "#",
    tags: ["react", "nextjs", "node", "framer"],
  },
  // {
  //   id: "07",
  //   key: 6,
  //   name: "avicta co",
  //   detail: "Digital Agency",
  //   imgurl: "/images/Avicta.png",
  //   url: "#",
  //   githuburl: "#",
  //   tags: ["react", "nextjs", "node", "framer"],
  // },
];

// import { AiFillGithub, AiFillFire } from "react-icons/ai";
// import { FaNodeJs, FaReact, FaPython } from "react-icons/fa";
// import { FaMobileAlt } from "react-icons/fa";
// import { FaSass } from "react-icons/fa";
// import {
//   SiJavascript,
//   SiTypescript,
//   SiDjango,
//   SiPython,
//   SiWebpack,
//   SiStyledComponents,
//   SiFramer,
//   SiHtml5,
//   SiNextDotJs,
// } from "react-icons/si";
// import { DiDjango } from "react-icons/di";

// const ProjectsListData = [
//   {
//     id: "01",
//     key: 1,
//     name: "avicta co",
//     detail: "digital agency website",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "02",
//     key: 2,
//     name: "zartaj",
//     detail: "landing page for UAE comapny",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "03",
//     key: 3,
//     name: "noor ul huda",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "04",
//     key: 4,
//     name: "avicta co",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "05",
//     key: 5,
//     name: "color pal",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
//   {
//     id: "06",
//     key: 6,
//     name: "avicta co",
//     detail: "abc",
//     imgurl: "/images/Avicta.png",
//     url: "#",
//     githuburl: "#",
//     tags: [<FaReact />, <SiNextDotJs />, <FaNodeJs />, <SiFramer />],
//   },
// ];

// export default ProjectsListData;
