import Head from 'next/head'

interface HeadProps {
    pathName: string
}

const HeadComp = (props: HeadProps) => {
    return (
    <Head>
        <title>Portfolio - {props.pathName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    )
}

export default HeadComp
